name: Update PR Description with Commits

on:
  pull_request:
    types:
      - closed  # Runs when a PR is closed

jobs:
  update-pr:
    if: github.event.pull_request.merged == true  # Only if PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Get commit hashes
        id: get_commits
        run: |
          COMMITS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
            | jq -r '.[].sha')

          # Convert commits into a formatted list
          FORMATTED_COMMITS=$(echo "$COMMITS" | awk '{print "- " $0}')

          # Store as output (not env) to avoid format issues
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$FORMATTED_COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update PR description
        run: |
          # Fetch current PR description
          DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            | jq -r '.body')

          # Append commits
          UPDATED_DESCRIPTION="$DESCRIPTION

          **Commits included in this PR:**
          $COMMITS"

          # Update PR description
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$UPDATED_DESCRIPTION\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
