name: Update PR Description with Commits

on:
  pull_request:
    types:
      - closed  # Trigger when PR is merged or closed

jobs:
  update-pr:
    if: github.event.pull_request.merged == true  # Only if PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get commit hashes
        id: get_commits
        run: |
          COMMITS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
            | jq -r '.[].sha')

          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
          echo "Commits found: $COMMITS"

      - name: Update PR description
        run: |
          DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
            | jq -r '.body')

          UPDATED_DESCRIPTION="$DESCRIPTION

          **Commits included in this PR:**
          $COMMITS"

          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$UPDATED_DESCRIPTION\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
